### PR TITLE
Build with utfproc8 and re2

### PR DESCRIPTION
**Pull request by jonkeane**

### CODE REVIEW

**Comment by jeroen** [comment]
OK I deployed this, but note that now you need to fix your R package, because you built w/ libre2, but currently in your R package you only link to with `-lre2` for rtools40, but not for the backport:

https://github.com/apache/arrow/blob/master/r/configure.win#L59

So you need to change that to link to `-lre2` unconditionally.

Before you submit to cran make sure to test on [winbuilder](http://win-builder.r-project.org/upload.aspx), in particular the `R-oldrelease` flavour, which uses this backport.

**Comment by jeroen** [comment]
Actually this doesn't seem to work with rtools35: https://win-builder.r-project.org/P5wwUznLPIRx/
I'll revert this for the backport.

**Comment by jeroen** [comment]
OK I have switched the backport to `-DARROW_WITH_RE2=OFF` and now it should probably work, as was intended in your configure script in the first place.

**Comment by jonkeane** [comment]
Thank you!

**Pull request merged**
