### PR TITLE
apache-arrow 0.14.1

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Comment by nealrichardson** [comment]
Odd, I pulled the SHA from https://www.apache.org/dist/arrow/arrow-0.14.1/apache-arrow-0.14.1.tar.gz.sha256. Is it problematic that the check fails (or is this why it was "SKIP" before)?

**Comment by jeroen** [comment]
I guess the files published on apache are different from the git tags

**Comment by nealrichardson** [comment]
Right, we should fetch from the apache source. I'll fix.

**Comment by nealrichardson** [comment]
Fixed, PTAL

**Pull request merged**
